name = "private-logger-frontend"
compatibility_date = "2024-11-01"

# Custom subdomain route
[[routes]]
pattern = "logger.chrisyaranga.dev/*"
zone_name = "chrisyaranga.dev"

# Deploy as Worker with static assets
[assets]
directory = "./dist"
not_found_handling = "single-page-application"
